---
title: "ch _3_submit"
output: html_document
date: '2023-11-14'
---


# Setup
## Directories and defaults

Ideally uses proj file for relative directories
see: https://yihui.org/knitr/options/

Directory structure  used in this analysis:

~/omz/wd
-- /output
-- /data
-- /figures
-- /r_wd
st_crs(temp)<-st_crs(ti)

~/omz/wd/r_wd
-- /Index
-- /Profiles
-- /r_objects
-- /r_scripts

```{r setup}
rm(list=ls())

r_scriptwd<-getwd()
wd<-substring(r_scriptwd,1,nchar(r_scriptwd) -10) # hardcoding replace here
knitr::opts_knit$set(root.dir = wd)
# relative directories
robj<-"r_objects"
fig<-"../../figures"
gis_data<-"../../data/gis_data"
output<-"../../output"
data_d<-"../../data"
cor_d<-"../../data/argo/coriolis_dac"
my_functions<-"r_scripts/submodules/BG_functions/"
# ocean_color<-"../../data/ocean_color_bud"
# bathy_d<-"../../data/bathy" # edit this
# olaf_profiles



knitr::opts_chunk$set(echo =FALSE)
#knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

# source
```{r}
source(paste0(my_functions, "ch2_functions.R"))
source(paste0(my_functions, "ch2_header.R"))
source(paste0(my_functions, "final_functions.R"))


f.ipak(packages)
rm(i)
## get metadata ##
# initialize_argo()

```
# load data for plottng final

```{r}
# data<-readRDS("r_objects/omz_change_whole_day.R")
data<-readRDS("r_objects/omz_change_juld_day.R")
temp<-readRDS("r_objects/ch2_seq_1_data.R")
h.pts<-temp$selected_zone_hurdat$h.pts
rm(temp)

```

```{r}
df<-data%>%bind_rows(.id = "group")
origin <- lubridate::ymd_hms('1950-01-01 00:00:00')
df$profile_date<-(origin + df$profile_JULD * 3600*24)
# df$decimal_day_dif<-round_date(df$overpass_time, unit="hour")+round_date(df$profile_date, unit="hour")

# x<-interval(round_date(df$overpass_time, unit="hour"),round_date(df$profile_date, unit="hour"))%>%as.period(., unit="hours") %>%as.numeric(., "hours")/24


x<-interval(round_date(df$overpass_time, unit="hour"),round_date(df$profile_date, unit="hour"))%>%as.period(., unit="days")%>%as.numeric(., "days")
# creates some erronous dates..

df$decimal_day_dif<-NA

z<-abs(abs(df$day_difference)-abs(x))

for(i in 1:dim(df)[1]){
 
 if(is.na(z[i])==F){
  if(z[i]<=3) {df$decimal_day_dif[i]<-x[i]} else {df$decimal_day_dif[i]<-df$day_difference[i]}
  if(is.na(df$decimal_day_dif[i])==F) {df$decimal_day_dif[i]<-df$decimal_day_dif[i]} else{df$decimal_day_dif[i]<-df$day_difference[i]}}
  else{df$decimal_day_dif[i]<-df$day_difference[i]}
  
}



# df$y_day<-yday(df$overpass_time)+df$day_difference
df<-f.match_tc_omz_change(h.pts, df)

df <- df %>% st_as_sf() %>%
  dplyr::mutate(lon = sf::st_coordinates(.)[,1],
                lat = sf::st_coordinates(.)[,2])

df<-filter(df, omz_value <= 500) # error or real?
df.after<-filter(df, day_difference >=0)
df.b4<-filter(df, day_difference <=-3)
```


```{r}
df <- df %>% st_as_sf() %>%
  dplyr::mutate(lon = sf::st_coordinates(.)[,1],
                lat = sf::st_coordinates(.)[,2])
```


# filter # 1

```{r}
x<-filter(df, distance_m <=200000)
```


## anova
```{r}
# one.way_df<-aov(omz_p ~ day_difference, data = df)
# one.way_df.after<-aov(omz_p ~ day_difference, data =df.after)
# two.way_df<-aov(omz_p ~ day_difference + distance_m, data = df)
# two.way_df.after<-aov(omz_p ~ day_difference + distance_m, data = df.after)
# 
# three.way_df<-aov(omz_p ~ day_difference + distance_m + Wind, data = df)
# three.way_df.after<-aov(omz_p ~ day_difference + distance_m + Wind, data = df.after)
# 
# three.way_x<-aov(omz_p ~ day_difference + distance_m + Wind, data = x)
# 
# y1<-sample_n(x, dim(x)[1]-100)
# y2<-sample_n(x, dim(x)[1]-200)
# y3<-sample_n(x, dim(x)[1]-500)
# 
# three.way_y1<-aov(omz_p ~ day_difference + distance_m + Wind, data = x)
# three.way_y2<-aov(omz_p ~ day_difference + distance_m + Wind, data = x)
# three.way_y3<-aov(omz_p ~ day_difference + distance_m + Wind, data = x)
# 
# four.way_df<-aov(omz_p ~ day_difference + distance_m + Wind +Key, data=df)
# four.way_df.after<-aov(omz_p ~ day_difference + distance_m + Wind +Key, data=df.after)
# 
# 
# five.way_df<-aov(omz_p ~ day_difference + distance_m + Wind +Key +Status, data=df)
# five.way_df.after<-aov(omz_p ~ day_difference + distance_m + Wind +Key+Status, data=df.after)
# 
# seven.way_df<-aov(omz_p ~ day_difference + distance_m + Wind +Key +Status +lon +lat, data=df)
# seven.way_df.after<-aov(omz_p ~ day_difference + distance_m + Wind +Key+Status +lon +lat, data=df.after)
# 
# 
# seven.way_chng_df<-aov(change_prior ~ day_difference + distance_m + Wind +Key +Status +lon +lat, data=df)
# seven.way_chng_df.after<-aov(change_prior ~ day_difference + distance_m + Wind +Key+Status +lon +lat, data=df.after)


multi.way_chng_df<-aov(change_prior ~ day_difference + distance_m + Wind +Key +Status +lon +lat + prior_min +var+prior_n + mean + median + range + max +y_day + omz_p, data=df)

multi.way_chng_df.after<-aov(change_prior ~ day_difference + distance_m + Wind +Key +Status +lon +lat + prior_min +var+prior_n + mean + median + range + max + y_day + omz_p, data=df.after)

multi.way_chng_df.b4<-aov(change_prior ~ day_difference + distance_m + Wind +Key +Status +lon +lat + prior_min +var+prior_n + mean + median + range + max + y_day + omz_p, data=df.b4)


multi.way_depth_df<-aov(omz_p ~ day_difference + distance_m + Wind +Key +Status +lon +lat + prior_min +var+prior_n + mean + median + range + max +y_day, data=na.omit(df))

# multi.way_depth_df.after<-aov(omz_p ~ day_difference + distance_m + Wind +Key +Status +lon +lat + prior_min +var+prior_n + mean + median + range + max + y_day, data=na.omit(df.after))

# multi.way_depth_df.b4<-aov(omz_p ~ day_difference + distance_m + Wind +Key +Status +lon +lat + prior_min +var + y_day, data=df.b4)

df.b4<-filter(df, day_difference <=-3)
multi.way_depth_df.b4<-aov(omz_p ~ day_difference + distance_m + Wind  +lon +lat + prior_min +var + y_day, data=df.b4)
y1<-sample_n(df.b4, dim(df.b4)[1]-100)
y2<-sample_n(df.b4, dim(df.b4)[1]-200)
y3<-sample_n(df.b4, dim(df.b4)[1]-500)
y1.a<-aov(omz_p ~ day_difference + distance_m + Wind  +lon +lat + prior_min +var + y_day, data=y1)
y2.a<-aov(omz_p ~ day_difference + distance_m +  Wind  +lon +lat + prior_min +var + y_day, data=y2)
y3.a<-aov(omz_p ~ day_difference + distance_m + Wind  +lon +lat + prior_min +var + y_day, data=y3)



```

```{r}
df.b4<-filter(df, day_difference <=-1)
multi.way_depth_df.b4<-aov(omz_p ~ day_difference + distance_m + Wind  +lon +lat + prior_min +var + y_day, data=df.b4)
y1<-sample_n(df.b4, dim(df.b4)[1]-200)
y2<-sample_n(df.b4, dim(df.b4)[1]-200)
y3<-sample_n(df.b4, dim(df.b4)[1]-200)
y1.a<-aov(omz_p ~ day_difference + distance_m + Wind  +lon +lat + prior_min +var + y_day, data=y1)
y2.a<-aov(omz_p ~ day_difference + distance_m +  Wind  +lon +lat + prior_min +var + y_day, data=y2)
y3.a<-aov(omz_p ~ day_difference + distance_m + Wind  +lon +lat + prior_min +var + y_day, data=y3)


print(dim(df.b4)[1])

print("anova depth b4")
summary(multi.way_depth_df.b4)

print("anova depth b4 y1")
summary(y1.a)
print("anova depth b4 y2")
summary(y2.a)

print("anova depth b4 y3")
summary(y3.a)


# random smapling n-200 makesa diffrence
```



## manova
```{r}

m.df<-cbind(df$omz_p, df$change_prior)
man.df<-manova(m.df ~ day_difference + distance_m + Wind +Key +Status +lon +lat + prior_min +var+prior_n + mean + median + range + max +y_day, data=df)
rm(m.df)


m.df.after<-cbind(df.after$omz_p, df.after$change_prior)
man.after<-aov(m.df.after ~ day_difference + distance_m + Wind +Key +Status +lon +lat + prior_min +var+prior_n + mean + median + range + max + y_day, data=df.after)
rm(m.df.after)

m.df.b4<-cbind(df.b4$omz_p, df.b4$change_prior)
man.b4<-aov(change_prior ~ day_difference + distance_m + Wind +Key +Status +lon +lat + prior_min +var+prior_n + mean + median + range + max + y_day, data=df.b4)
rm(m.df.b4)



```


### manova sensitivty
```{r}

m.df.after<-cbind(df.after$omz_p, df.after$change_prior)
man.after<-aov(m.df.after ~ day_difference + distance_m + Wind +Key +Status +lon +lat + prior_min +var+prior_n + mean + median + range + max + y_day, data=df.after)
rm(m.df.after)


y1<-sample_n(df.after, dim(df.after)[1]-200)
y2<-sample_n(df.after, dim(df.after)[1]-200)
y3<-sample_n(df.after, dim(df.after)[1]-200)

y1.m<-cbind(y1$omz_p, y1$change_prior )
y1.m<-aov(y1.m ~ day_difference + distance_m + Wind +Key +Status +lon +lat + prior_min +var+prior_n + mean + median + range + max + y_day, data=y1)

y2.m<-cbind(y2$omz_p, y2$change_prior )
y2.m<-aov(y2.m ~ day_difference + distance_m + Wind +Key +Status +lon +lat + prior_min +var+prior_n + mean + median + range + max + y_day, data=y2)

y3.m<-cbind(y3$omz_p, y3$change_prior )
y3.m<-aov(y3.m ~ day_difference + distance_m + Wind +Key +Status +lon +lat + prior_min +var+prior_n + mean + median + range + max + y_day, data=y3)

```


```{r}


print(dim(df.b4)[1])

print("manova after")
summary(man.after)

print("manova depth b4 y1")
summary(y1.m)
print("manova depth b4 y2")
summary(y2.m)

print("manova depth b4 y3")
summary(y3.m)

```



# use me
```{r}
# print("manova all")
# summary(man.df)

# print("manova b4")
# summary(man.b4)

print("anova depth b4")
summary(multi.way_depth_df.b4)


print("manova after")
summary(man.after)


```



```{r}
summary(three.way_x)
summary(three.way_y1)
summary(three.way_y2)
summary(three.way_y3)

summary(four.way_df)

summary(four.way_df.after)

```

```{r}

# summary(seven.way_df)
# 
# summary(seven.way_df.after)

# summary(seven.way_chng_df)

# summary(seven.way_chng_df.after)
print("depth all")
summary(multi.way_depth_df)
print("depth b4")
summary(multi.way_depth_df.b4)
print("depth after ")
summary(multi.way_depth_df.after)

print("change all")
summary(multi.way_chng_df)
print("change b4")
summary(multi.way_chng_df.b4)
print("change after")
summary(multi.way_chng_df.after)


```








# load data for omz calcultion

```{r}
data<-readRDS("r_objects/selected_profiles_list.R")

f.rm_new<-function(x){
x<-x[sapply(x, function(y) dim(y)[1]) > 0]
return(x)}
f.rm_one<-function(x){
  if(length(x)==2){x<-x} else {x<-NULL}
  return(x)
}

#remove empties
data<-lapply(data, f.rm_new)
data<-lapply(data, f.rm_one)
data<-compact(data)

```

```{r}
z<-data[[261]]

y<-f.pressure_of_omz_v3(z)


t261<-f.final_match_v3(z)

f.rm_new<-function(x){
x<-x[sapply(x, function(y) dim(y)[1]) > 0]
return(x)}

data_new<-lapply(data, f.rm_new)

f.rm_one<-function(x){
  if(length(x)==2){x<-x} else {x<-NULL}
  return(x)
}

date_newer<-lapply(data_new, f.rm_one)


```


```{r}
rm(z, t87)
```



```{r}

t1<-vector(mode = "list", length=length(data))
for(i in 1:length(data)){
t1[[i]]<-f.final_match_v3(data[[i]])
  
}


```


## try
```{r}
# omz_change_decimal_day<-lapply(data, f.final_match_v2)
# omz_change_whole_day<-lapply(data, f.final_match_v3)

omz_change_juld_day<-lapply(data, f.final_match_v3)


```


```{r}
setwd(wd)
saveRDS(omz_change_juld_day, "r_objects/omz_change_juld_day.R")
```





#data split_lists
```{r}

data<-readRDS("r_objects/ch2_seq_1_data.R")
all<-data$tc_search_radi_profiles$km_500$tc
rm(data)


x<-lapply(all, f.remove)
x<-purrr::list_flatten(x)
rm(all)

```



```{r}
Sys.time()
print(Sys.time())
selected_profiles_list<-lapply(x, f.get_profiles)
# saveRDS(selected_profiles_list, "r_objects/olaf_match.R")
Sys.time()
print(Sys.time())
```

```{r}
# saveRDS(selected_profiles_list, "r_objects/selected_profiles_list.R")
test<-readRDS("r_objects/selected_profiles_list.R")

```



```{r}
omz_change<-lapply(x, f.final_match)
saveRDS(omz_change, "r_objects/olaf_match.R")
Sys.time()
print(Sys.time())

```






















