---
title: "poc_flux_and_TC_and_CHl_and_SST"
author: "Brandon M. Genco"
date: "06/15/2022"
output: html_document
---


# Setup
## Directories and defaults
Use r proj file for relative directories
see: https://yihui.org/knitr/options/


```{r setup}
rm(list=ls())
# relative directories
robj<-"r_objects"
fig<-"../../figures"

output<-"../../output"

#absolute directory
# drop_img<-"/home/brandon/Dropbox/MERCED/dissertation/presentations/images"

knitr::opts_chunk$set(echo =FALSE, warning = FALSE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

```

## packages

Installed custom hurdat package using r markdown menu
* download  tar from archive as no longer maintained on cran repository
* https://cran.r-project.org/src/contrib/Archive/HURDAT/
+ include as git submodule instead

```{r}
f.ipak <- function(pkg){
  # loads packages, quietly, given by a vector of package names e.g., pkg<-c("ggplot", "tidyverse")
  # will install  packages listed , and their dependencies, if needed.
  new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
  if (length(new.pkg))
    install.packages(new.pkg, dependencies = TRUE, quiet=T, verbose = F)
  sapply(pkg, require, character.only = TRUE, quietly = FALSE, warn.conflicts=F)
}

# packages<-c("stars", "gridExtra", "cowplot", "sf", "ggspatial","stringr","sp", "rgdal",  "rgeos", "raster","readr" ,"tidyverse", "ggplot2", "lubridate",  "ggthemes", "data.table", "reshape2", "RColorBrewer", "marmap", "extrafont", "oce", "MODIS", "measurements")  # set packages here

# tidyverse: is all of the following packages: ggplot2, dplyr, tidyr, readr, purr, tibble, sringr, & forcats.

packages<-c("sp", "rgdal",  "rgeos", "raster", "readr", "tidyverse", "lubridate",  "ggthemes",  "sf", "cmocean", "ncdf4", "RNetCDF",  "plot3D", "tidync", "devtools", "stars", "ncmeta", "maps", "oce", "data.table", "fasterize", "RStoolbox", "scales", "purrr")

# "HURDAT",

f.ipak(packages)
# lapply(packages, require, character.only = TRUE)
# rm(f.ipak, packages)
print(paste0("Current Working Directory is ", getwd()))

wd<-getwd()
```

# load basic

```{r}
h<-readRDS("r_objects/hurdat.R")
h$DateTime<-with_tz(h$DateTime, tz="UTC")
```

# plotting v1
```{r}
setwd(wd)
setwd(robj)

# data<-read_rds("vgpm_integrated_20220512.R")
data<-read_rds("vgpm_integrated_all_years_202200607.R")

x<-data$st5
x$date<-ymd(x$date)

x<-select(x, date, `mean_export_flux (mgC/m^2/day) for_window_area (total/sum_grid_area)`, `total_export_flux (mgC/day)`)
# x<-select(x, date, `total_export_flux (mgC/day)` )

names(x)<-c("date", "avg", "ef")
x$ef<-x$ef/1000000

# x$l<-log10(x$ef)
total<- ggplot(x, aes(x=date, y=ef)) +
  geom_point()+
  ylab("Export flux (kg C/day)")+
  xlab("8-day Integration")+
  labs(title="Station 3.5 Total Export flux for 40,000 km^2 area",
  caption = "2018- Tropical Cyclone Season: non-lagged EF")+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(plot.caption =element_text(hjust = 0.5))+
  scale_y_continuous(labels = function(x) format(x, scientific = TRUE))


average<- ggplot(x, aes(x=date, y=avg)) +
  geom_point()+
  ylab("Mean export flux (mgC/m^2/day)")+
  xlab("8-day Integration")+
  labs(title="Station 3.5 Average Export flux for 40,000 km^2 area",
       caption = "2018- Tropical Cyclone Season: non-lagged EF")+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(plot.caption =element_text(hjust = 0.5))+
  scale_y_continuous(labels = function(x) format(x, scientific = TRUE))

```



# plotting v2

```{r}


# setwd(wd)
# setwd(robj)
# 
# # data<-read_rds("vgpm_integrated_20220512.R")
# data<-read_rds("vgpm_integrated_all_years_202200607.R")


# f.poc_plots<-function(x){}
# see https://stackoverflow.com/questions/9469504/access-and-preserve-list-names-in-lapply-function


plots_avg<-vector(mode="list", length(data))
plots_total<-vector(mode="list", length(data))
station_number<-c("1", "2", "3", "3.5", "4", "5")
window_area<-c(round((data$st1$`window_area (m^2)`[1]*1e-6),0), round((data$st2$`window_area (m^2)`[1]*1e-6),0), round((data$st3$`window_area (m^2)`[1]*1e-6),0), round((data$st3.5$`window_area (m^2)`[1]*1e-6),0), round((data$st4$`window_area (m^2)`[1]*1e-6),0), round((data$st5$`window_area (m^2)`[1]*1e-6),0))



rects<- data.frame(x1=seq(as.Date('2002-05-15'), length.out=20, by="years"),
        x2=seq(as.Date('2002-11-30'),length.out=20, by="years"))

rects$y1<-Inf
rects$y2<-Inf

# rectangel parameters:
rect_color<-NA
sz<-0.25
alph<-.25
rect_fill<-"cornsilk1"


for(i in 1:length(data)) {

  
# x<-data$st5
x<-data[[i]]
lab_avg<-paste0("Station ", station_number[i], ":", " Average Export Flux - ", window_area[i], " km^2 area")
lab_total<-paste0("Station ", station_number[i], ":", " Total Export Flux - ", window_area[i], " km^2 area")

x$date<-ymd(x$date)
x<-select(x, date, `mean_export_flux (mgC/m^2/day) for_window_area (total/sum_grid_area)`, `total_export_flux (mgC/day)`)
# x<-select(x, date, `total_export_flux (mgC/day)` )

names(x)<-c("date", "avg", "ef")
x$ef<-x$ef/1000000

# x$l<-log10(x$ef)
plots_total[[i]]<- ggplot(x, aes(x=date, y=ef)) +
  geom_rect(data =x ,  aes(xmin =rects$x1[1], xmax = rects$x2[1] , ymin = -Inf, ymax = Inf), fill=rect_fill, colour=rect_color, size=sz, alpha=alph)+
  geom_rect(data =x ,  aes(xmin =rects$x1[2], xmax = rects$x2[2] , ymin = -Inf, ymax = Inf), fill=rect_fill, colour=rect_color, size=sz, alpha=alph)+
  geom_rect(data =x ,  aes(xmin =rects$x1[3], xmax = rects$x2[3] , ymin = -Inf, ymax = Inf), fill=rect_fill, colour=rect_color, size=sz, alpha=alph)+
  geom_rect(data =x ,  aes(xmin =rects$x1[4], xmax = rects$x2[4] , ymin = -Inf, ymax = Inf), fill=rect_fill, colour=rect_color, size=sz, alpha=alph)+
  geom_rect(data =x ,  aes(xmin =rects$x1[5], xmax = rects$x2[5] , ymin = -Inf, ymax = Inf), fill=rect_fill, colour=rect_color, size=sz, alpha=alph)+
  geom_rect(data =x ,  aes(xmin =rects$x1[6], xmax = rects$x2[6] , ymin = -Inf, ymax = Inf), fill=rect_fill, colour=rect_color, size=sz, alpha=alph)+
  geom_rect(data =x ,  aes(xmin =rects$x1[7], xmax = rects$x2[7] , ymin = -Inf, ymax = Inf), fill=rect_fill, colour=rect_color, size=sz, alpha=alph)+
  geom_rect(data =x ,  aes(xmin =rects$x1[8], xmax = rects$x2[8] , ymin = -Inf, ymax = Inf), fill=rect_fill, colour=rect_color, size=sz, alpha=alph)+
  geom_rect(data =x ,  aes(xmin =rects$x1[9], xmax = rects$x2[9] , ymin = -Inf, ymax = Inf), fill=rect_fill, colour=rect_color, size=sz, alpha=alph)+
  geom_rect(data =x ,  aes(xmin =rects$x1[10], xmax = rects$x2[10] , ymin = -Inf, ymax = Inf), fill=rect_fill, colour=rect_color, size=sz, alpha=alph)+
  geom_rect(data =x ,  aes(xmin =rects$x1[11], xmax = rects$x2[11] , ymin = -Inf, ymax = Inf), fill=rect_fill, colour=rect_color, size=sz, alpha=alph)+
  geom_rect(data =x ,  aes(xmin =rects$x1[12], xmax = rects$x2[12] , ymin = -Inf, ymax = Inf), fill=rect_fill, colour=rect_color, size=sz, alpha=alph)+
  geom_rect(data =x ,  aes(xmin =rects$x1[13], xmax = rects$x2[13] , ymin = -Inf, ymax = Inf), fill=rect_fill, colour=rect_color, size=sz, alpha=alph)+
  geom_rect(data =x ,  aes(xmin =rects$x1[14], xmax = rects$x2[14] , ymin = -Inf, ymax = Inf), fill=rect_fill, colour=rect_color, size=sz, alpha=alph)+
  geom_rect(data =x ,  aes(xmin =rects$x1[15], xmax = rects$x2[15] , ymin = -Inf, ymax = Inf), fill=rect_fill, colour=rect_color, size=sz, alpha=alph)+
  geom_rect(data =x ,  aes(xmin =rects$x1[16], xmax = rects$x2[16] , ymin = -Inf, ymax = Inf), fill=rect_fill, colour=rect_color, size=sz, alpha=alph)+
  geom_rect(data =x ,  aes(xmin =rects$x1[17], xmax = rects$x2[17] , ymin = -Inf, ymax = Inf), fill=rect_fill, colour=rect_color, size=sz, alpha=alph)+
  geom_rect(data =x ,  aes(xmin =rects$x1[18], xmax = rects$x2[18] , ymin = -Inf, ymax = Inf), fill=rect_fill, colour=rect_color, size=sz, alpha=alph)+
  geom_rect(data =x ,  aes(xmin =rects$x1[19], xmax = rects$x2[19] , ymin = -Inf, ymax = Inf), fill=rect_fill, colour=rect_color, size=sz, alpha=alph)+
  geom_rect(data =x ,  aes(xmin =rects$x1[20], xmax = rects$x2[20] , ymin = -Inf, ymax = Inf), fill=rect_fill, colour=rect_color, size=sz, alpha=alph)+
  geom_point()+
  theme_bw()+
  ylab("Export flux (kg C/day)")+
  labs(title=lab_total,
  caption = "8-Day resolution: Non-lagged EF. Colored boxes: Climatological Cyclone Season (05-15 to 11-30)")+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(plot.caption =element_text(hjust = 0.5))+
  scale_y_continuous(labels = function(x) format(x, scientific = TRUE))+
  scale_x_date(date_breaks = "1 years", date_labels = "%Y", date_minor_breaks = "6 months")+
  theme(axis.title.x=element_blank())
 

#, date_minor_breaks = "1 month"

 # xlab("8-day Integration")+
plots_avg[[i]]<- ggplot(x, aes(x=date, y=avg)) +
  geom_rect(data =x ,  aes(xmin =rects$x1[1], xmax = rects$x2[1] , ymin = -Inf, ymax = Inf), fill=rect_fill, colour=rect_color, size=sz, alpha=alph)+
  geom_rect(data =x ,  aes(xmin =rects$x1[2], xmax = rects$x2[2] , ymin = -Inf, ymax = Inf), fill=rect_fill, colour=rect_color, size=sz, alpha=alph)+
  geom_rect(data =x ,  aes(xmin =rects$x1[3], xmax = rects$x2[3] , ymin = -Inf, ymax = Inf), fill=rect_fill, colour=rect_color, size=sz, alpha=alph)+
  geom_rect(data =x ,  aes(xmin =rects$x1[4], xmax = rects$x2[4] , ymin = -Inf, ymax = Inf), fill=rect_fill, colour=rect_color, size=sz, alpha=alph)+
  geom_rect(data =x ,  aes(xmin =rects$x1[5], xmax = rects$x2[5] , ymin = -Inf, ymax = Inf), fill=rect_fill, colour=rect_color, size=sz, alpha=alph)+
  geom_rect(data =x ,  aes(xmin =rects$x1[6], xmax = rects$x2[6] , ymin = -Inf, ymax = Inf), fill=rect_fill, colour=rect_color, size=sz, alpha=alph)+
  geom_rect(data =x ,  aes(xmin =rects$x1[7], xmax = rects$x2[7] , ymin = -Inf, ymax = Inf), fill=rect_fill, colour=rect_color, size=sz, alpha=alph)+
  geom_rect(data =x ,  aes(xmin =rects$x1[8], xmax = rects$x2[8] , ymin = -Inf, ymax = Inf), fill=rect_fill, colour=rect_color, size=sz, alpha=alph)+
  geom_rect(data =x ,  aes(xmin =rects$x1[9], xmax = rects$x2[9] , ymin = -Inf, ymax = Inf), fill=rect_fill, colour=rect_color, size=sz, alpha=alph)+
  geom_rect(data =x ,  aes(xmin =rects$x1[10], xmax = rects$x2[10] , ymin = -Inf, ymax = Inf), fill=rect_fill, colour=rect_color, size=sz, alpha=alph)+
  geom_rect(data =x ,  aes(xmin =rects$x1[11], xmax = rects$x2[11] , ymin = -Inf, ymax = Inf), fill=rect_fill, colour=rect_color, size=sz, alpha=alph)+
  geom_rect(data =x ,  aes(xmin =rects$x1[12], xmax = rects$x2[12] , ymin = -Inf, ymax = Inf), fill=rect_fill, colour=rect_color, size=sz, alpha=alph)+
  geom_rect(data =x ,  aes(xmin =rects$x1[13], xmax = rects$x2[13] , ymin = -Inf, ymax = Inf), fill=rect_fill, colour=rect_color, size=sz, alpha=alph)+
  geom_rect(data =x ,  aes(xmin =rects$x1[14], xmax = rects$x2[14] , ymin = -Inf, ymax = Inf), fill=rect_fill, colour=rect_color, size=sz, alpha=alph)+
  geom_rect(data =x ,  aes(xmin =rects$x1[15], xmax = rects$x2[15] , ymin = -Inf, ymax = Inf), fill=rect_fill, colour=rect_color, size=sz, alpha=alph)+
  geom_rect(data =x ,  aes(xmin =rects$x1[16], xmax = rects$x2[16] , ymin = -Inf, ymax = Inf), fill=rect_fill, colour=rect_color, size=sz, alpha=alph)+
  geom_rect(data =x ,  aes(xmin =rects$x1[17], xmax = rects$x2[17] , ymin = -Inf, ymax = Inf), fill=rect_fill, colour=rect_color, size=sz, alpha=alph)+
  geom_rect(data =x ,  aes(xmin =rects$x1[18], xmax = rects$x2[18] , ymin = -Inf, ymax = Inf), fill=rect_fill, colour=rect_color, size=sz, alpha=alph)+
  geom_rect(data =x ,  aes(xmin =rects$x1[19], xmax = rects$x2[19] , ymin = -Inf, ymax = Inf), fill=rect_fill, colour=rect_color, size=sz, alpha=alph)+
  geom_rect(data =x ,  aes(xmin =rects$x1[20], xmax = rects$x2[20] , ymin = -Inf, ymax = Inf), fill=rect_fill, colour=rect_color, size=sz, alpha=alph)+
  geom_point()+
  theme_bw()+
  ylab("Mean export flux (mgC/m^2/day)")+
  scale_y_continuous(labels = function(x) format(x, scientific = TRUE))+
  scale_x_date(date_breaks = "2 years", date_labels = "%Y", date_minor_breaks = "6 months")+
  labs(title=lab_avg, caption = "8-Day resolution: Non-lagged EF. Colored boxes: Climatological Cyclone Season (05-15 to 11-30)")+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(plot.caption =element_text(hjust = 0.5))+
  scale_x_date(date_breaks = "1 years", date_labels = "%Y", date_minor_breaks = "6 months")+
  theme(axis.title.x=element_blank())
   
rm(x)         
                       
}

```


```{r}
library(cowplot)
setwd(wd)
setwd(fig)
a1<-list(plots_avg[[1]], plots_avg[[2]], plots_avg[[3]])
a2<-list(plots_avg[[4]], plots_avg[[5]], plots_avg[[6]])

pdf("poc_averages_1.pdf", height=8.5 , width =11)
cowplot::plot_grid(plotlist = a1, nrow=3, ncol=1)
dev.off()

pdf("poc_averages_2.pdf", height=8.5 , width =11)
cowplot::plot_grid(plotlist = a2, nrow=3, ncol=1)
dev.off()

t1<-list(plots_total[[1]], plots_total[[2]], plots_total[[3]])
t2<-list(plots_total[[4]], plots_total[[5]], plots_total[[6]])

pdf("poc_totals_1.pdf", height=8.5 , width =11)
cowplot::plot_grid(plotlist = t1, nrow=3, ncol=1)
dev.off()

pdf("poc_totals_2.pdf", height=8.5 , width =11)
cowplot::plot_grid(plotlist = t2, nrow=3, ncol=1)
dev.off()



```




creating boxes

```{r}



rects<- data.frame(x1=seq(as.Date('2002-05-15'), length.out=20, by="years"),
        x2=seq(as.Date('2002-11-30'),length.out=20, by="years"))

rects$y1<-Inf
rects$y2<-Inf
rects$x1[1]<-as.Date("2002-07-05")

rect_color<-"grey89"


ggplot(x, aes(x = time)) + 
  
geom_rect(data =x ,  aes(xmin =rects$x1[1], xmax = rects$x2[1] , ymin = -Inf, ymax = Inf), fill=rect_color)
geom_rect(data =x ,  aes(xmin =rects$x1[2], xmax = rects$x2[2] , ymin = -Inf, ymax = Inf), fill=rect_color) +
geom_rect(data =x ,  aes(xmin =rects$x1[3], xmax = rects$x2[3] , ymin = -Inf, ymax = Inf), fill=rect_color) +
geom_rect(data =x ,  aes(xmin =rects$x1[4], xmax = rects$x2[4] , ymin = -Inf, ymax = Inf), fill=rect_color) +
geom_rect(data =x ,  aes(xmin =rects$x1[5], xmax = rects$x2[5] , ymin = -Inf, ymax = Inf), fill=rect_color) +
geom_rect(data =x ,  aes(xmin =rects$x1[6], xmax = rects$x2[6] , ymin = -Inf, ymax = Inf), fill=rect_color) +
theme_bw()



```



plotting (old cod fro chl, tmep and staion boxes) suplemtary figure

```{r}
i<-4
x<-data[[i]]
x$date<-ymd(x$date)
x<-select(x, date, `mean_export_flux (mgC/m^2/day) for_window_area (total/sum_grid_area)`, `total_export_flux (mgC/day)`)
# x<-select(x, date, `total_export_flux (mgC/day)` )

rect_color<-"red"

names(x)<-c("date", "avg", "ef")
x$ef<-x$ef/1000000

t<- ggplot(x, aes(x=date, y=ef)) +
  geom_rect(data =x ,  aes(xmin =rects$x1[1], xmax = rects$x2[1] , ymin = -Inf, ymax = Inf), fill=NA, colour=rect_color, size=0.5, alpha=0.2)+
  geom_point()+
  ylab("Export flux (kg C/day)")+
  labs(title=lab_total,
  caption = "8-Day resolution: non-lagged EF")+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(plot.caption =element_text(hjust = 0.5))+
  scale_y_continuous(labels = function(x) format(x, scientific = TRUE))+
  scale_x_date(date_breaks = "2 years", date_labels = "%Y", date_minor_breaks = "6 months")+
  theme(axis.title.x=element_blank())




```


```




